#!/usr/bin/env bash

set -euo pipefail

VERSION="1.0.0"
SCRIPT_NAME="$(basename "$0")"
SSH_GUARD_USER="flyyjarvis"
SSH_GUARD_SCRIPT="/usr/local/bin/ssh-guard.sh"
SSH_GUARD_CONFIG="/etc/ssh-guard.conf"
LOG_FILE="/var/log/ssh-guard.log"
BACKUP_SUFFIX=".ssh-guard-backup.$(date +%Y%m%d-%H%M%S)"

usage() {
    cat <<EOF
SSH Guard Setup Script v${VERSION}

Usage: $SCRIPT_NAME [OPTIONS]

Automatically deploys ssh-guard.sh as a safe command filter for AI agent SSH access.

Options:
    -h, --help          Show this help message
    -u, --user USER     SSH user for AI agent (default: $SSH_GUARD_USER)
    -k, --key FILE      SSH public key file to install
    -m, --mode MODE     Security mode: strict|standard|audit-only (default: standard)
    -d, --dry-run       Show what would be done without executing
    -f, --force         Force overwrite existing installation
    --uninstall         Remove ssh-guard installation

Examples:
    $SCRIPT_NAME -k ~/.ssh/ai-agent.pub
    $SCRIPT_NAME -u aibot -k ./agent-key.pub -m strict
    $SCRIPT_NAME --dry-run
    $SCRIPT_NAME --uninstall

EOF
}

log() {
    echo "[$(date '+%H:%M:%S')] $*" >&2
}

error() {
    echo "[ERROR] $*" >&2
    exit 1
}

require_root() {
    if [[ $EUID -ne 0 ]]; then
        error "This script must be run as root. Use: sudo $0 $*"
    fi
}

backup_file() {
    local file="$1"
    if [[ -f "$file" ]]; then
        cp "$file" "${file}${BACKUP_SUFFIX}"
        log "Backed up $file to ${file}${BACKUP_SUFFIX}"
    fi
}

check_dependencies() {
    local missing=()
    for cmd in useradd usermod ssh-keygen; do
        if ! command -v "$cmd" >/dev/null 2>&1; then
            missing+=("$cmd")
        fi
    done
    if [[ ${#missing[@]} -gt 0 ]]; then
        error "Missing required commands: ${missing[*]}"
    fi
}

create_user() {
    local username="$1"
    if id "$username" >/dev/null 2>&1; then
        log "User $username already exists"
    else
        useradd -m -s /bin/bash -c "SSH Guard AI Agent" "$username"
        log "Created user: $username"
    fi
    
    # Ensure home directory exists
    local home_dir
    home_dir="$(getent passwd "$username" | cut -d: -f6)"
    if [[ ! -d "$home_dir" ]]; then
        mkdir -p "$home_dir"
        chown "$username:$username" "$home_dir"
        chmod 750 "$home_dir"
    fi
}

setup_ssh_key() {
    local username="$1" keyfile="$2"
    local home_dir ssh_dir auth_keys
    
    home_dir="$(getent passwd "$username" | cut -d: -f6)"
    ssh_dir="$home_dir/.ssh"
    auth_keys="$ssh_dir/authorized_keys"
    
    # Create .ssh directory
    if [[ ! -d "$ssh_dir" ]]; then
        mkdir -p "$ssh_dir"
        chown "$username:$username" "$ssh_dir"
        chmod 700 "$ssh_dir"
        log "Created $ssh_dir"
    fi
    
    # Install public key
    if [[ ! -f "$keyfile" ]]; then
        error "SSH key file not found: $keyfile"
    fi
    
    # Validate key format
    if ! ssh-keygen -l -f "$keyfile" >/dev/null 2>&1; then
        error "Invalid SSH public key: $keyfile"
    fi
    
    # Add key with ForceCommand
    local key_content force_cmd
    key_content="$(cat "$keyfile")"
    force_cmd='command="'$SSH_GUARD_SCRIPT'",no-port-forwarding,no-x11-forwarding,no-agent-forwarding,no-pty'
    
    echo "$force_cmd $key_content" >> "$auth_keys"
    chown "$username:$username" "$auth_keys"
    chmod 600 "$auth_keys"
    log "Installed SSH key for $username with ForceCommand"
}

install_script() {
    local script_dir
    script_dir="$(dirname "$SSH_GUARD_SCRIPT")"
    
    # Create directory if needed
    mkdir -p "$script_dir"
    
    # Copy script
    if [[ -f "ssh-guard.sh" ]]; then
        cp "ssh-guard.sh" "$SSH_GUARD_SCRIPT"
    else
        error "ssh-guard.sh not found in current directory"
    fi
    
    # Set permissions
    chown root:root "$SSH_GUARD_SCRIPT"
    chmod 755 "$SSH_GUARD_SCRIPT"
    log "Installed $SSH_GUARD_SCRIPT"
}

create_config() {
    local mode="$1"
    
    if [[ -f "$SSH_GUARD_CONFIG" ]] && [[ "$FORCE" != "1" ]]; then
        log "Config file $SSH_GUARD_CONFIG already exists (use --force to overwrite)"
        return
    fi
    
    backup_file "$SSH_GUARD_CONFIG"
    
    cat > "$SSH_GUARD_CONFIG" <<EOF
# SSH Guard Configuration
# Generated by $SCRIPT_NAME on $(date)

# Security mode: strict | standard | audit-only
mode=$mode

# Webhook URL for notifications (optional)
# webhook_url=https://your-webhook.example.com/ssh-guard

# Custom allow patterns (regex)
# allow_pattern[]=^cat /etc/hostname$
# allow_pattern[]=^ls /opt/myapp

# Custom block patterns (regex)  
# block_pattern[]=dangerous-command
# block_pattern[]=.*secret.*

# Grey zone controls (1=enabled, 0=disabled)
grey_cp=1
grey_tee=1
grey_docker_exec=0
grey_tmp_writes=1
EOF

    chown root:root "$SSH_GUARD_CONFIG"
    chmod 644 "$SSH_GUARD_CONFIG"
    log "Created config: $SSH_GUARD_CONFIG"
}

setup_logging() {
    local log_dir
    log_dir="$(dirname "$LOG_FILE")"
    
    # Create log directory
    mkdir -p "$log_dir"
    
    # Create log file
    touch "$LOG_FILE"
    chown root:root "$LOG_FILE"
    chmod 644 "$LOG_FILE"
    log "Setup logging: $LOG_FILE"
    
    # Setup logrotate
    if command -v logrotate >/dev/null 2>&1; then
        cat > /etc/logrotate.d/ssh-guard <<EOF
$LOG_FILE {
    daily
    rotate 30
    compress
    delaycompress
    missingok
    notifempty
    create 644 root root
}
EOF
        log "Created logrotate config for $LOG_FILE"
    fi
}

test_installation() {
    local username="$1"
    
    log "Testing installation..."
    
    # Test script syntax
    if bash -n "$SSH_GUARD_SCRIPT"; then
        log "✓ Script syntax check passed"
    else
        error "✗ Script syntax check failed"
    fi
    
    # Test with safe command
    local test_result
    if test_result=$(sudo -u "$username" SSH_ORIGINAL_COMMAND="echo test" "$SSH_GUARD_SCRIPT" 2>&1); then
        log "✓ Safe command test passed"
    else
        log "✗ Safe command test failed: $test_result"
    fi
    
    # Test with dangerous command
    if test_result=$(sudo -u "$username" SSH_ORIGINAL_COMMAND="rm -rf /" "$SSH_GUARD_SCRIPT" 2>&1); then
        log "✗ Dangerous command was NOT blocked: $test_result"
    else
        log "✓ Dangerous command correctly blocked"
    fi
    
    log "Installation test completed"
}

uninstall() {
    log "Uninstalling SSH Guard..."
    
    # Remove script
    if [[ -f "$SSH_GUARD_SCRIPT" ]]; then
        rm -f "$SSH_GUARD_SCRIPT"
        log "Removed $SSH_GUARD_SCRIPT"
    fi
    
    # Remove config (with confirmation)
    if [[ -f "$SSH_GUARD_CONFIG" ]]; then
        read -p "Remove config file $SSH_GUARD_CONFIG? (y/N): " -r
        if [[ $REPLY =~ ^[Yy]$ ]]; then
            rm -f "$SSH_GUARD_CONFIG"
            log "Removed $SSH_GUARD_CONFIG"
        fi
    fi
    
    # Remove user (with confirmation)
    if id "$SSH_GUARD_USER" >/dev/null 2>&1; then
        read -p "Remove user $SSH_GUARD_USER? (y/N): " -r
        if [[ $REPLY =~ ^[Yy]$ ]]; then
            userdel -r "$SSH_GUARD_USER" 2>/dev/null || true
            log "Removed user $SSH_GUARD_USER"
        fi
    fi
    
    # Remove logrotate config
    if [[ -f /etc/logrotate.d/ssh-guard ]]; then
        rm -f /etc/logrotate.d/ssh-guard
        log "Removed logrotate config"
    fi
    
    log "Uninstall completed"
}

show_summary() {
    local username="$1" keyfile="$2" mode="$3"
    
    cat <<EOF

==================================================
SSH Guard Installation Summary
==================================================

User:           $username
Script:         $SSH_GUARD_SCRIPT  
Config:         $SSH_GUARD_CONFIG
Logs:           $LOG_FILE
Mode:           $mode
SSH Key:        $keyfile

To test the connection:
    ssh $username@$(hostname)

The AI agent will be restricted to read-only operations.
Check $LOG_FILE for command audit logs.

Edit $SSH_GUARD_CONFIG to customize security policies.

==================================================
EOF
}

# Parse command line arguments
DRY_RUN=0
FORCE=0
MODE="standard"
SSH_KEY_FILE=""
UNINSTALL=0

while [[ $# -gt 0 ]]; do
    case $1 in
        -h|--help)
            usage
            exit 0
            ;;
        -u|--user)
            SSH_GUARD_USER="$2"
            shift 2
            ;;
        -k|--key)
            SSH_KEY_FILE="$2"
            shift 2
            ;;
        -m|--mode)
            MODE="$2"
            shift 2
            ;;
        -d|--dry-run)
            DRY_RUN=1
            shift
            ;;
        -f|--force)
            FORCE=1
            shift
            ;;
        --uninstall)
            UNINSTALL=1
            shift
            ;;
        *)
            error "Unknown option: $1"
            ;;
    esac
done

# Validate mode
case "$MODE" in
    strict|standard|audit-only) ;;
    *) error "Invalid mode: $MODE. Must be strict, standard, or audit-only" ;;
esac

# Main execution
main() {
    require_root
    check_dependencies
    
    if [[ "$UNINSTALL" == "1" ]]; then
        uninstall
        exit 0
    fi
    
    if [[ -z "$SSH_KEY_FILE" ]]; then
        error "SSH key file is required. Use -k/--key option."
    fi
    
    if [[ "$DRY_RUN" == "1" ]]; then
        log "DRY RUN - showing what would be done:"
        log "1. Create user: $SSH_GUARD_USER"
        log "2. Install script: $SSH_GUARD_SCRIPT"
        log "3. Create config: $SSH_GUARD_CONFIG (mode: $MODE)"
        log "4. Install SSH key: $SSH_KEY_FILE"
        log "5. Setup logging: $LOG_FILE"
        log "6. Test installation"
        exit 0
    fi
    
    log "Starting SSH Guard installation..."
    
    create_user "$SSH_GUARD_USER"
    install_script
    create_config "$MODE"
    setup_ssh_key "$SSH_GUARD_USER" "$SSH_KEY_FILE"
    setup_logging
    test_installation "$SSH_GUARD_USER"
    show_summary "$SSH_GUARD_USER" "$SSH_KEY_FILE" "$MODE"
    
    log "Installation completed successfully!"
}

main "$@"